name: ammn
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  flutter_animation_progress_bar: ^2.3.1
  flutter_animate: ^4.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-ExtraLight.ttf
          weight: 300
        - asset: fonts/Tajawal-Light.ttf
          weight: 400
        - asset: fonts/Tajawal-Regular.ttf
          weight: 500
        - asset: fonts/Tajawal-Medium.ttf
          weight: 600
        - asset: fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: fonts/Tajawal-Black.ttf
          weight: 900


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image_logo.png"
  min_sdk_android: 21